baseURL: https://shayanamani.com
languageCode: en-us
title: Shayan Amani | A Personal Platform
theme: hugo-PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    author: Me
    # author: ["Me", "You"] # multiple authors

    images: ["<link or path of image for opengraph, twitter-cards>"]

    ShowReadingTime: true
    ShowShareButtons: true
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Shayan Amani
        # subtitle: Just a Subtitle
        # imageUrl: /SHi-ON_squared_shadow.png
        imageTitle: Shayan Amani
        buttons:
            - name: Archive
              url: archive
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: github
          url: "https://github.com/SHi-ON"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/3782119/shayan-amani"
        - name: twitter
          url: "https://twitter.com/com_shayanamani"
        - name: linkedin
          url: "https://www.linkedin.com/in/shayanamani"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

menu:
    main:
        - identifier: archive
          name: Blog Archive
          url: /archive/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        