[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  [[redirects]]
  from = "/resume"
  to = "https://api.mysearch.com"
  status = 301
  force = true # COMMENT: ensure that we always redirect
