[build]
  publish = "public"
  command = "make publish"

[context.production.environment]

  [[redirects]]
  from = "/resume"
  to = "/ShayanAmaniResume.pdf"
  status = 301
  force = true # COMMENT: ensure that we always redirect
